#!/usr/bin/env bash

bar() {
    percent=$1
    length=20

    # Clamp biar aman
    [ "$percent" -gt 100 ] && percent=100
    [ "$percent" -lt 0 ] && percent=0

    filled=$(( percent * length / 100 ))
    empty=$(( length - filled ))

    bar=""
    space=""

    [ "$filled" -gt 0 ] && bar=$(printf "%0.s=" $(seq 1 $filled))
    [ "$empty" -gt 0 ] && space=$(printf "%0.s-" $(seq 1 $empty))

    echo "$bar$space"
}

case "$1" in
    mute)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
        ;;
    up)
        wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
        ;;
    down)
        wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-
        ;;
esac

# Poll sampai value update (max ~0.1s)
for i in {1..5}; do
    VOL_INFO=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    sleep 0.02
done

PERCENT=$(echo "$VOL_INFO" | awk '{print int($2 * 100)}')
BAR=$(bar $PERCENT)

if echo "$VOL_INFO" | grep -q MUTED; then
    notify-send -t 1000 -r 999 "Muted" "····+!+····"
else
    notify-send -t 1000 -r 999 "Volume: $PERCENT%" "$BAR"
fi