#!/usr/bin/env bash

# Small delay to allow session initialization
sleep 0.5

### DBUS
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

### CURSOR
xsetroot -cursor_name left_ptr &

### HOTKEY
pgrep -x sxhkd >/dev/null || sxhkd &

### WALLPAPER
pgrep -x feh >/dev/null || \
feh --no-fehbg --bg-fill "$HOME/.config/bspwm/wallpaper/Sinon-3.jpg" &

### NOTIFICATION
pgrep -x dunst >/dev/null || dunst &

### POLKIT
pgrep -x polkit-gnome-authentication-agent-1 >/dev/null || \
/usr/libexec/polkit-gnome-authentication-agent-1 &

### AUDIO fallback
(
sleep 1
pgrep -x pipewire >/dev/null || pipewire
pgrep -x wireplumber >/dev/null || wireplumber
) &

### COMPOSITOR
pgrep -x picom >/dev/null || ~/.config/picom/auto.sh &

### BAR
pgrep -x polybar >/dev/null || ~/.config/polybar/launch.sh &

### MONITOR HOTPLUG
pgrep -f monitor >/dev/null || ~/.config/sxhkd/scripts/monitor &